### ISSUE TITLE
Для статистики не хватает тестовых данных "траты по категории за период в процентах"

### ISSUE THREAD

**Issue by AndreyGorbushin** [HalyavinKV/ShopperMobileiOS#11]
Сейчас запрос "summaries/categories/spend" за определенные периоды выдает список трат пользователя по категориям. Там есть сумма и процент. Сумма заполнена, а процент везде (вроде) равен 0. Надо процент тоже заполнить, т.к. он необходим для построения круговой диаграммы трат.

**Comment by HalyavinKV** [comment]
Исправлено. Процент для итогов по категориям заполняется. Также сократили количество категорий. Теперь выводится только top 7 категорий + одна предопределенная "Прочее"
