### ISSUE TITLE
Дата создания/активации акции, чтобы понимать, в каком месте лены её отображать

### ISSUE THREAD

**Issue by VladimirAbakumov** [HalyavinKV/ShopperMobileiOS#12]
Для корректного расположения акций в ленте было бы прикольно иметь какую-то дату, к примеру, создания активации, а, возможно, дату получения акции клиентом. Дата создания уже имеется. Какую будем использовать?

**Comment by HalyavinKV** [comment]
Обсудили. Добавил в акцию свойство showedDate - дата, ранее которой не нужно показывать акцию в ленте
