### ISSUE TITLE
Категория Прочее в Статистике

### ISSUE THREAD

**Issue by AndreyGorbushin** [HalyavinKV/ShopperMobileiOS#15]
Необходима ли возможность отображения "подкатегорий" для категории Прочее? Сейчас для этой категории в подкатегориях приходит только "Прочее". Пока убрал возможность перехода на подкатегории по этой категории.

Также если для категории "Прочее" сумма расходов 0 - эту категорию не отображаю.

**Comment by HalyavinKV** [comment]
Все правильно сделал
