### ISSUE TITLE
Прямые ссылки на картинки

### ISSUE THREAD

**Issue by taraskreknin** [HalyavinKV/ShopperMobileiOS#5]
В акциях сейчас приходят не прямые ссылки на картинки, типа
http://dev.businessculture.ru:9080/Shopper.Portal/logos/?stock=7
Можно сразу возвращать такие?
http://izhtrading.ru/pictures/content/111111.jpg

**Comment by HalyavinKV** [comment]
Картинки хостироваться будут у нас. Сейчас смущает что нет имени файла?

**Comment by taraskreknin** [comment]
По первой ссылке в ответ приходит строка, а не картинка, получается нам надо сделать запрос акций, потом по каждой акции сделать запрос url картинки и потом еще скачать саму картинку. Слишком уж сложно.

**Comment by HalyavinKV** [comment]
А это. Там в БД просто мусор был, Сейчас должно быть нормально
