### ISSUE TITLE
Количество сэкономленных средств для экрана Статистика

### ISSUE THREAD

**Issue by AndreyGorbushin** [HalyavinKV/ShopperMobileiOS#7]
При запросе, например, http://dev.businessculture.ru:9080/Shopper.Rest/summaries/profit?retailer=220023547B544144A983A964760B4F6D&buyerID=4861982&cardID=4421544&startDate=01.2.2017&finishDate=28.2.2017 выдается ответ со статусом 204. 
Если у пользователя нет сэкономленных средств за данный период, то сервер же должен возвращать 200 статус код и ответ 0?

**Comment by HalyavinKV** [comment]
Исправлено. Теперь если данных нет, то возвращается 0
