### ISSUE TITLE
Прогресс по скидке на экране Статистика

### ISSUE THREAD

**Issue by AndreyGorbushin** [HalyavinKV/ShopperMobileiOS#8]
Каким образом получить размер следующей скидки и сколько до нее осталось?

**Comment by HalyavinKV** [comment]
В текущей версии приложения, не планируется выводить данную информацию. Пока можно оставить статическую информацию, как нарисована в дизайне

**Comment by AndreyGorbushin** [comment]
А когда планируется выводить? Если планируется выдать конечному пользователю приложение без данной информации, то надо совсем ее не отображать.

**Comment by HalyavinKV** [comment]
~~Тогда убираем совсем. Сейчас приложение ориентируется на торговую сеть, в которой система скидок не накопительная, а индивидуальная для каждого товара~~
Переговорил с представителем торговой сети, они все таки планируют делать накопительные скидки. Будем делать

**Comment by HalyavinKV** [comment]
Добавили в сущность Карта два свойства nextDiscount и nextDiscountBuy они могут быть null. Если хотя бы одно из них не заполнено, то отображать прогресс и надпись "До скидки 20% еще 2000 ₽" не нужно. Иначе надпись выводим. В тестовых данных эти свойства заполнили
Пример /buyers?retailer=220023547B544144A983A964760B4F6D&buyerID=4861987
```json
{
   "id": 4861987,   
   "cards":    [
            {
         "id": 3170158,
         "number": "3170158",
         "name": "Дисконтная карта",
         "owner": "Покупатель №3170158",
         "image": "http://localhost:8080/Shopper.Portal/logos/?card=3170158",
         "discount": 4,
         "totalBuy": 34355.9,
         "totalDiscount": 795.86,
         *"nextDiscount": 5,*
         *"nextDiscountBuy": 5004,*
         "cardDate": "27.06.2007 00:00:00",
         "firstDateCheck": "04.01.2016 12:37:00",
         "type": "Material"
      }
   ],
```
}
