### ISSUE TITLE
Размер скидки на экране Статистика

### ISSUE THREAD

**Issue by AndreyGorbushin** [HalyavinKV/ShopperMobileiOS#9]
Как определить размер скидки за выбранный период? Высчитывать так: размер скидки = (количество сэкономленных средств за период / количество затраченных средств за период) * 100%? Или есть какой нибудь запрос для этого?

**Comment by HalyavinKV** [comment]
Добавили метод /summaries/discount - возвращает размер скидки в % за указанный период.
Пример. /summaries/discount?retailer=220023547B544144A983A964760B4F6D&buyerID=4861987&startDate=01.02.2016&finishDate=28.02.2017
